// <auto-generated />
using System;
using CVIS.Unity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVIS.Unity.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260320063608_InitialUnitySchema")]
    partial class InitialUnitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("unity")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PlatformBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastSNOWTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlatformBaselines", "unity");
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyDriftEval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaselinePolicyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyDriftEvalDetailsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RunTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolicyDriftEval", "unity");
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyDriftEvalDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriftVersion")
                        .HasColumnType("int");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolicyDriftEvalDetails", "unity");
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PolicyEvents", "unity");
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PlatformBaseline", b =>
                {
                    b.OwnsOne("CVIS.Unity.Core.Entities.PlatformBaseline.Attributes#Dictionary", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PlatformBaselineId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PlatformBaselineId");

                            b1.ToTable("PlatformBaselines", "unity");

                            b1.ToJson("Attributes");

                            b1.WithOwner()
                                .HasForeignKey("PlatformBaselineId");
                        });

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "AttributesHash", b1 =>
                        {
                            b1.Property<Guid>("PlatformBaselineId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PlatformBaselineId");

                            b1.ToTable("PlatformBaselines", "unity");

                            b1.ToJson("AttributesHash");

                            b1.WithOwner()
                                .HasForeignKey("PlatformBaselineId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("AttributesHash")
                        .IsRequired();
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyDriftEval", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "Differences", b1 =>
                        {
                            b1.Property<Guid>("PolicyDriftEvalId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PolicyDriftEvalId");

                            b1.ToTable("PolicyDriftEval", "unity");

                            b1.ToJson("Differences");

                            b1.WithOwner()
                                .HasForeignKey("PolicyDriftEvalId");
                        });

                    b.Navigation("Differences");
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyDriftEvalDetail", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PolicyDriftEvalDetailId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PolicyDriftEvalDetailId");

                            b1.ToTable("PolicyDriftEvalDetails", "unity");

                            b1.ToJson("Attributes");

                            b1.WithOwner()
                                .HasForeignKey("PolicyDriftEvalDetailId");
                        });

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "AttributesHash", b1 =>
                        {
                            b1.Property<Guid>("PolicyDriftEvalDetailId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PolicyDriftEvalDetailId");

                            b1.ToTable("PolicyDriftEvalDetails", "unity");

                            b1.ToJson("AttributesHash");

                            b1.WithOwner()
                                .HasForeignKey("PolicyDriftEvalDetailId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("AttributesHash")
                        .IsRequired();
                });

            modelBuilder.Entity("CVIS.Unity.Core.Entities.PolicyEvent", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "Metadata", b1 =>
                        {
                            b1.Property<long>("PolicyEventId")
                                .HasColumnType("bigint");

                            b1.HasKey("PolicyEventId");

                            b1.ToTable("PolicyEvents", "unity");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("PolicyEventId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
